# Read Data 

In [28]:
import pandas as pd
from warnings import filterwarnings
filterwarnings("ignore")
A=pd.read_csv("K:/DATA SCIENCE/Deep Learning/Google_Stock_Price_Train.csv")
A.tail(20)

Date    Open    High     Low   Close     Volume
1238   12/2/2016  744.59  754.00  743.10   750.5  1,452,500
1239   12/5/2016  757.71  763.90  752.90  762.52  1,394,200
1240   12/6/2016  764.73  768.83  757.34  759.11  1,690,700
1241   12/7/2016  761.00  771.36  755.80  771.19  1,761,000
1242   12/8/2016  772.48  778.18  767.23  776.42  1,488,100
1243   12/9/2016  780.00  789.43  779.02  789.29  1,821,900
1244  12/12/2016  785.04  791.25  784.35  789.27  2,104,100
1245  12/13/2016  793.90  804.38  793.34   796.1  2,145,200
1246  12/14/2016  797.40  804.00  794.01  797.07  1,704,200
1247  12/15/2016  797.34  803.00  792.92  797.85  1,626,500
1248  12/16/2016  800.40  800.86  790.29   790.8  2,443,800
1249  12/19/2016  790.22  797.66  786.27   794.2  1,232,100
1250  12/20/2016  796.76  798.65  793.27  796.42    951,000
1251  12/21/2016  795.84  796.68  787.10  794.56  1,211,300
1252  12/22/2016  792.36  793.32  788.58  791.26    972,200
1253  12/23/2016  790.90  792.74  787.28  789.91    623,400
1254  12/27/2016  790.68  797.86  787.66  791.55    789,100
1255  12/28/2016  793.70  794.23  783.20  785.05  1,153,800
1256  12/29/2016  783.33  785.93  778.92  782.79    744,300
1257  12/30/2016  782.75  782.78  770.41  771.82  1,770,000

In [29]:
A.isna().sum()

Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [30]:
trd=A[['Open']]
trd.head(20)

Open
0   325.25
1   331.27
2   329.83
3   328.34
4   322.04
5   313.70
6   310.59
7   314.43
8   311.96
9   314.81
10  312.14
11  319.30
12  294.16
13  291.91
14  292.07
15  287.68
16  284.92
17  284.32
18  287.95
19  290.41

# Changed Training Data into Array

In [31]:
import numpy as np
trd=np.array(trd)
trd[1:50]

array([[331.27],
       [329.83],
       [328.34],
       [322.04],
       [313.7 ],
       [310.59],
       [314.43],
       [311.96],
       [314.81],
       [312.14],
       [319.3 ],
       [294.16],
       [291.91],
       [292.07],
       [287.68],
       [284.92],
       [284.32],
       [287.95],
       [290.41],
       [291.38],
       [291.34],
       [294.23],
       [296.39],
       [302.44],
       [303.18],
       [304.87],
       [302.81],
       [304.11],
       [304.63],
       [305.32],
       [300.28],
       [301.36],
       [300.81],
       [304.84],
       [302.37],
       [302.54],
       [302.16],
       [303.86],
       [308.14],
       [309.97],
       [309.84],
       [309.06],
       [302.89],
       [303.39],
       [303.88],
       [302.84],
       [298.88],
       [303.24],
       [306.35]])

# Feature Scaling

In [32]:
from sklearn.preprocessing import MinMaxScaler
mms=MinMaxScaler()
mms.fit_transform(trd)

array([[0.08581368],
       [0.09701243],
       [0.09433366],
       ...,
       [0.95725128],
       [0.93796041],
       [0.93688146]])

# Create Data For Training

In [33]:
trd.shape

(1258, 1)

In [34]:
xtrain=[]
ytrain=[]
for i in range(50,1258,1):
    xtrain.append(trd[i-50:i])
    ytrain.append(trd[i:i+1])

In [35]:
print(xtrain[2],"\n") 
print(ytrain[2])

[[329.83]
 [328.34]
 [322.04]
 [313.7 ]
 [310.59]
 [314.43]
 [311.96]
 [314.81]
 [312.14]
 [319.3 ]
 [294.16]
 [291.91]
 [292.07]
 [287.68]
 [284.92]
 [284.32]
 [287.95]
 [290.41]
 [291.38]
 [291.34]
 [294.23]
 [296.39]
 [302.44]
 [303.18]
 [304.87]
 [302.81]
 [304.11]
 [304.63]
 [305.32]
 [300.28]
 [301.36]
 [300.81]
 [304.84]
 [302.37]
 [302.54]
 [302.16]
 [303.86]
 [308.14]
 [309.97]
 [309.84]
 [309.06]
 [302.89]
 [303.39]
 [303.88]
 [302.84]
 [298.88]
 [303.24]
 [306.35]
 [307.15]
 [309.29]] 

[[310.4]]


In [36]:
type(xtrain)

list

In [37]:
xtr=np.array(xtrain)   #changed in array

In [38]:
xtr.shape

(1208, 50, 1)

In [39]:
ytr=np.array(ytrain)   #changed in array

In [40]:
ytr.shape

(1208, 1, 1)

# LSTM

In [41]:
import keras
from keras.layers import LSTM,Dense,Dropout
from keras.models import Sequential
from keras.callbacks import EarlyStopping

In [42]:
es=EarlyStopping(patience=50)
nn=Sequential()
nn.add(LSTM(50,return_sequences=True,input_shape=(50,1)))
nn.add(LSTM(100,return_sequences=True))
nn.add(Dropout(0.2))
nn.add(LSTM(100,return_sequences=True))
nn.add(Dropout(0.1))
nn.add(Dense(1))

In [43]:
nn.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mean_absolute_error'])
nn.fit(xtr,ytr,epochs=400,validation_split=0.2,callbacks=es)

Epoch 1/400
31/31 [==============================] - 19s 200ms/step - loss: 485.0385 - mean_absolute_error: 485.0385 - val_loss: 730.6747 - val_mean_absolute_error: 730.6747
Epoch 2/400
31/31 [==============================] - 4s 130ms/step - loss: 476.8937 - mean_absolute_error: 476.8937 - val_loss: 726.5782 - val_mean_absolute_error: 726.5784
Epoch 3/400
31/31 [==============================] - 4s 136ms/step - loss: 473.1234 - mean_absolute_error: 473.1234 - val_loss: 722.9824 - val_mean_absolute_error: 722.9824
Epoch 4/400
31/31 [==============================] - 4s 133ms/step - loss: 469.5906 - mean_absolute_error: 469.5905 - val_loss: 719.5180 - val_mean_absolute_error: 719.5179
Epoch 5/400
31/31 [==============================] - 4s 133ms/step - loss: 466.1690 - mean_absolute_error: 466.1690 - val_loss: 716.1262 - val_mean_absolute_error: 716.1262
Epoch 6/400
31/31 [==============================] - 4s 134ms/step - loss: 462.7997 - mean_absolute_error: 462.7998 - val_loss: 712.78

# Testing Data

In [44]:
tst_data=pd.read_csv("K:/DATA SCIENCE/Deep Learning/Google_Stock_Price_Test.csv")

In [45]:
#as you can see i have only 20 rows...so i cannot test this data. i have to concat this data with training data
tst_data[['Open']]

Open
0   778.81
1   788.36
2   786.08
3   795.26
4   806.40
5   807.86
6   805.00
7   807.14
8   807.48
9   807.08
10  805.81
11  805.12
12  806.91
13  807.25
14  822.30
15  829.62
16  837.81
17  834.71
18  814.66
19  796.86

In [46]:
test_concat=pd.concat([A,tst_data])
test_concat.shape

(1278, 6)

In [47]:
P=test_concat[['Open']].values

In [48]:
xtest=[]
for i in range(1258,1277,1):
    xtest.append(P[i-50:i])

In [49]:
xtest[1]

array([[795.  ],
       [804.9 ],
       [816.68],
       [806.34],
       [801.  ],
       [808.35],
       [795.47],
       [782.89],
       [778.2 ],
       [767.25],
       [750.66],
       [774.5 ],
       [783.4 ],
       [779.94],
       [791.17],
       [756.54],
       [755.6 ],
       [746.97],
       [755.2 ],
       [766.92],
       [771.37],
       [762.61],
       [772.63],
       [767.73],
       [764.26],
       [760.  ],
       [771.53],
       [770.07],
       [757.44],
       [744.59],
       [757.71],
       [764.73],
       [761.  ],
       [772.48],
       [780.  ],
       [785.04],
       [793.9 ],
       [797.4 ],
       [797.34],
       [800.4 ],
       [790.22],
       [796.76],
       [795.84],
       [792.36],
       [790.9 ],
       [790.68],
       [793.7 ],
       [783.33],
       [782.75],
       [778.81]])

In [50]:
xts=np.array(xtest) #changed in array
xts.shape

(19, 50, 1)

In [51]:
nn.predict(xts)

1/1 [==============================] - 8s 8s/step


array([[[397.31702],
        [501.5688 ],
        [517.54767],
        [519.749  ],
        [520.04767],
        [520.08813],
        [520.09357],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.0944 ],
        [520.